[package]
name = "aoc"
version = "0.1.0"
edition = "2024"

[dependencies]
bitvec = "1.0.1"
good_lp = { version = "1.14.2", default-features = false, features = [
  "microlp",
] }
nalgebra = "0.34.1"
ndarray = "0.14"
ndarray-linalg = "0.13"
